from __future__ import annotations

import re
from datetime import datetime
from typing import Literal

import markdown2
from jinja2 import Template

from app.agents.summarizer import ContentSummary, PaperSummary, ResearchSynthesis


class ReportValidationError(Exception):
	"""Raised when report validation fails."""


class ReportService:
	"""Builds markdown and HTML reports from synthesized research output."""

	# HTML template for rendering reports
	HTML_TEMPLATE = Template("""<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>{{ title }}</title>
	<style>
		body {
			font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
			line-height: 1.6;
			color: #333;
			max-width: 900px;
			margin: 0 auto;
			padding: 20px;
			background-color: #f9f9f9;
		}
		.header {
			border-bottom: 3px solid #0066cc;
			padding-bottom: 20px;
			margin-bottom: 30px;
		}
		h1 {
			color: #0066cc;
			margin: 0 0 10px 0;
		}
		.metadata {
			color: #666;
			font-size: 0.9em;
			margin-top: 10px;
		}
		h2 {
			color: #0088dd;
			border-left: 4px solid #0066cc;
			padding-left: 10px;
			margin-top: 30px;
		}
		h3 {
			color: #004499;
			margin-top: 20px;
		}
		.section {
			background-color: white;
			padding: 15px;
			margin: 15px 0;
			border-radius: 5px;
			box-shadow: 0 2px 4px rgba(0,0,0,0.1);
		}
		ul, ol {
			margin: 10px 0;
			padding-left: 20px;
		}
		li {
			margin: 5px 0;
		}
		.source {
			background-color: #f0f0f0;
			padding: 10px;
			border-radius: 3px;
			margin: 10px 0;
			font-size: 0.9em;
		}
		.source a {
			color: #0066cc;
			text-decoration: none;
		}
		.source a:hover {
			text-decoration: underline;
		}
		code {
			background-color: #f4f4f4;
			padding: 2px 6px;
			border-radius: 3px;
			font-family: 'Courier New', monospace;
		}
		.validation-badge {
			display: inline-block;
			background-color: #4CAF50;
			color: white;
			padding: 5px 10px;
			border-radius: 3px;
			font-size: 0.85em;
			margin-right: 10px;
		}
		.footer {
			margin-top: 40px;
			padding-top: 20px;
			border-top: 1px solid #ddd;
			color: #666;
			font-size: 0.9em;
			text-align: center;
		}
	</style>
</head>
<body>
	<div class="header">
		<h1>{{ title }}</h1>
		<div class="metadata">
			<strong>Topic:</strong> {{ topic }}<br>
			<strong>Generated:</strong> {{ generated_date }}<br>
			{% if validation_status %}<span class="validation-badge">{{ validation_status }}</span>{% endif %}
		</div>
	</div>
	
	<div class="section">
		<h2>Overview</h2>
		{{ overview_html | safe }}
	</div>
	
	{% if key_themes %}
	<div class="section">
		<h2>Key Themes</h2>
		<ul>
		{% for theme in key_themes %}
			<li>{{ theme }}</li>
		{% endfor %}
		</ul>
	</div>
	{% endif %}
	
	<div class="section">
		<h2>Cross-Source Synthesis</h2>
		{{ synthesis_html | safe }}
	</div>
	
	{% if paper_summaries_html %}
	<div class="section">
		<h2>Paper Summaries</h2>
		{{ paper_summaries_html | safe }}
	</div>
	{% endif %}
	
	{% if content_summaries_html %}
	<div class="section">
		<h2>Web Content Summaries</h2>
		{{ content_summaries_html | safe }}
	</div>
	{% endif %}
	
	<div class="footer">
		<p>This report was generated by the Agentic AI Research Engine.</p>
	</div>
</body>
</html>""")

	def generate_markdown_report(self, synthesis: ResearchSynthesis) -> str:
		"""Generate a markdown report from a synthesized research payload."""
		lines: list[str] = [
			f"# Research Report: {synthesis.topic}",
			"",
			"## Overview",
			synthesis.overview or "No overview generated.",
			"",
			"## Key Themes",
		]

		if synthesis.key_themes:
			lines.extend(f"- {theme}" for theme in synthesis.key_themes)
		else:
			lines.append("- No key themes generated.")

		lines.extend(["", "## Cross-Source Synthesis", synthesis.synthesis or "No synthesis generated.", ""])

		if synthesis.paper_summaries:
			lines.append("## Paper Summaries")
			lines.extend(self._render_paper_summary(item) for item in synthesis.paper_summaries)
			lines.append("")

		if synthesis.content_summaries:
			lines.append("## Web Content Summaries")
			lines.extend(self._render_content_summary(item) for item in synthesis.content_summaries)
			lines.append("")

		return "\n".join(lines).strip() + "\n"

	def generate_html_report(self, synthesis: ResearchSynthesis, validate: bool = True) -> str:
		"""Generate an HTML report from a synthesized research payload."""
		if validate:
			self.validate_synthesis(synthesis)

		# Convert markdown sections to HTML
		overview_html = markdown2.markdown(synthesis.overview or "No overview generated.")
		synthesis_html = markdown2.markdown(synthesis.synthesis or "No synthesis generated.")

		# Render paper summaries
		paper_summaries_html = ""
		if synthesis.paper_summaries:
			for summary in synthesis.paper_summaries:
				paper_summaries_html += self._render_paper_summary_html(summary)

		# Render content summaries
		content_summaries_html = ""
		if synthesis.content_summaries:
			for summary in synthesis.content_summaries:
				content_summaries_html += self._render_content_summary_html(summary)

		# Render the HTML template
		html = self.HTML_TEMPLATE.render(
			title=f"Research Report: {synthesis.topic}",
			topic=synthesis.topic,
			generated_date=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
			validation_status="✓ Validated" if validate else None,
			overview_html=overview_html,
			key_themes=synthesis.key_themes or [],
			synthesis_html=synthesis_html,
			paper_summaries_html=paper_summaries_html,
			content_summaries_html=content_summaries_html,
		)

		return html

	def validate_synthesis(self, synthesis: ResearchSynthesis) -> dict[str, bool | str]:
		"""Validate the completeness and structure of a research synthesis.
		
		Returns a dict with validation results. Raises ReportValidationError if critical issues found.
		"""
		issues: list[str] = []
		warnings: list[str] = []

		# Check required fields
		if not synthesis.topic:
			issues.append("topic is required")
		if not synthesis.overview:
			warnings.append("overview is empty")
		if not synthesis.synthesis:
			warnings.append("synthesis is empty")

		# Check content lists
		if not synthesis.key_themes:
			warnings.append("no key themes generated")
		if not synthesis.paper_summaries and not synthesis.content_summaries:
			warnings.append("no summaries generated")

		# Check synthesis structure
		if synthesis.overview and len(synthesis.overview.strip()) < 10:
			warnings.append("overview is too short")

		if synthesis.synthesis and len(synthesis.synthesis.strip()) < 10:
			warnings.append("synthesis is too short")

		if issues:
			raise ReportValidationError(f"Validation failed: {'; '.join(issues)}")

		return {
			"is_valid": len(issues) == 0,
			"issues": issues,
			"warnings": warnings,
		}

	def validate_report(self, report: str, format_type: Literal["markdown", "html"] = "markdown") -> dict[str, bool | int | str]:
		"""Validate a generated report for completeness and format correctness."""
		issues: list[str] = []

		# Basic content checks
		if not report or len(report.strip()) == 0:
			issues.append("report is empty")
		else:
			if len(report.strip()) < 50:
				issues.append("report is too short")

			if format_type == "markdown":
				# Check markdown structure
				if not re.search(r"^#\s", report, re.MULTILINE):
					issues.append("no main heading found")
				if not re.search(r"^##\s", report, re.MULTILINE):
					issues.append("no section headings found")

			elif format_type == "html":
				# Check HTML structure
				if not report.strip().startswith("<!DOCTYPE html"):
					issues.append("missing DOCTYPE declaration")
				if "<html" not in report.lower():
					issues.append("missing html tag")
				if "<body" not in report.lower():
					issues.append("missing body tag")
				if "</html>" not in report.lower():
					issues.append("missing closing html tag")

		return {
			"is_valid": len(issues) == 0,
			"format": format_type,
			"length": len(report),
			"issues": issues,
		}

	@staticmethod
	def _render_paper_summary(summary: PaperSummary) -> str:
		findings = "\n".join(f"- {item}" for item in summary.key_findings if item)
		return (
			f"### {summary.title}\n"
			f"Source: {summary.url}\n\n"
			f"Key Findings:\n{findings or '- None'}\n\n"
			f"Methodology: {summary.methodology or 'Not provided.'}\n\n"
			f"Implications: {summary.implications or 'Not provided.'}\n\n"
			f"Summary: {summary.summary or 'Not provided.'}\n"
		)

	@staticmethod
	def _render_content_summary(summary: ContentSummary) -> str:
		points = "\n".join(f"- {item}" for item in summary.main_points if item)
		return (
			f"### {summary.title}\n"
			f"Source: {summary.url}\n\n"
			f"Main Points:\n{points or '- None'}\n\n"
			f"Summary: {summary.summary or 'Not provided.'}\n"
		)

	@staticmethod
	def _render_paper_summary_html(summary: PaperSummary) -> str:
		"""Render a paper summary as HTML."""
		findings = "\n".join(f"<li>{item}</li>" for item in summary.key_findings if item)
		return f"""
		<div class="section">
			<h3>{summary.title}</h3>
			<div class="source">
				<strong>Source:</strong> <a href="{summary.url}" target="_blank">{summary.url}</a>
			</div>
			<strong>Key Findings:</strong>
			<ul>
				{findings or '<li>None</li>'}
			</ul>
			<p><strong>Methodology:</strong> {summary.methodology or 'Not provided.'}</p>
			<p><strong>Implications:</strong> {summary.implications or 'Not provided.'}</p>
			<p><strong>Summary:</strong> {summary.summary or 'Not provided.'}</p>
		</div>
		"""

	@staticmethod
	def _render_content_summary_html(summary: ContentSummary) -> str:
		"""Render a content summary as HTML."""
		points = "\n".join(f"<li>{item}</li>" for item in summary.main_points if item)
		return f"""
		<div class="section">
			<h3>{summary.title}</h3>
			<div class="source">
				<strong>Source:</strong> <a href="{summary.url}" target="_blank">{summary.url}</a>
			</div>
			<strong>Main Points:</strong>
			<ul>
				{points or '<li>None</li>'}
			</ul>
			<p><strong>Summary:</strong> {summary.summary or 'Not provided.'}</p>
		</div>
		"""
